sudo: required

cache:
  directories:
  - $HOME/.m2

language: java

jdk:
  - oraclejdk8

services:
  - docker

install: mvn -U install --quiet -DskipTests=true

script: mvn test coveralls:report -Pwith-coverage-report
