sudo: required

cache:
  directories:
  - $HOME/.m2

language: java

jdk:
  - oraclejdk8

services:
  - docker

install: mvn -U install --quiet -Dskip.unit.tests=true -Dskip.integration.tests=true

script: mvn verify coveralls:report -Pwith-coverage-report
