sudo: required

cache:
  directories:
  - $HOME/.m2

language: java

jdk:
  - oraclejdk8

services:
  - docker
  
install: travis_wait mvn install

script: mvn clean verify coveralls:report -Pwith-coverage-report
