server:
  port: 8081
  
info:
  version: @project.version@

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true
    
spring:
  profiles:
    active: h2,insecure
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false    
  jpa:
    hibernate:
      ddl-auto: none
  jackson:
    serialization-inclusion: non-empty
    
flyway:
  placeholders:
    preamble:
    varcharQualifier: 
    createTableSuffix:
    longVarBinary:
    
---

spring:
  profiles: h2
  datasource:
    url: jdbc:h2:mem:grivetdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    data-source-class-name: org.h2.jdbcx.JdbcDataSource
    username: sa
    password: sa

flyway:
  locations: classpath:db/migration, classpath:db/users
  placeholders:
    autoInc: AUTO_INCREMENT
    dateFormatFn: FORMATDATETIME(val, 'yyyy-MM-dd')
    dateTimeFormatFn: CONCAT(FORMATDATETIME(val, 'yyyy-MM-dd'), 'T', FORMATDATETIME(val, 'HH:mm:ss'))
    instantFormatFn: CONCAT(FORMATDATETIME(val, 'yyyy-MM-dd'), 'T', FORMATDATETIME(val, 'HH:mm:ss'))
    textColumnType: TEXT
    longTextColumnType: LONGTEXT
    longVarBinary: LONGBLOB
    renameTableKeyword: RENAME TO
    alterColumnKeyword: ALTER COLUMN
    
---

spring:
  profiles: mysql
  datasource:
    url: jdbc:mariadb://localhost:3306/grivetdb
    driver-class-name: org.mariadb.jdbc.Driver
    data-source-class-name: org.mariadb.jdbc.MariaDbDataSource
    username: root
    password: jackal#3

flyway:
  locations: classpath:db/with_partitions, classpath:db/users
  placeholders:
    preamble: |
      /*!40101 SET character_set_client = utf8mb4 */;
      /*!40101 SET global innodb_file_format = BARRACUDA */;
      /*!40101 SET global innodb_large_prefix = ON */;
    autoInc: AUTO_INCREMENT 
    dateFormatFn: DATE_FORMAT(val, '%Y-%m-%d')
    dateTimeFormatFn: DATE_FORMAT(val, '%Y-%m-%dT%T')
    instantFormatFn: DATE_FORMAT(val, '%Y-%m-%dT%T')
    textColumnType: TEXT
    longTextColumnType: LONGTEXT
    longVarBinary: LONGBLOB
    varcharQualifier: CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
    createTableSuffix: ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC
    renameTableKeyword: RENAME
    alterColumnKeyword: MODIFY
        
---

spring:
  profiles: docker
  profiles.include: mysql,insecure
  cloud:
    config:
      enabled: true
    discovery:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
    
monitoring:
  statsd:
    enabled: true
    hostname: graphite
    
---

spring:
  profiles: secure
  
stormpath:
  authorized:
    group:
      admin: https://api.stormpath.com/v1/groups/kXMXDjb68vjzmjpCi8XVZ
      user: https://api.stormpath.com/v1/groups/yEMNvN4kQmswQtWmR7eqv
---

spring:
  profiles: insecure

management:
  security:
    enabled: false
    
security:
  basic:
    enabled: false
    
stormpath:
  enabled: false
    
---

spring:
  profiles: https

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-password: password
  