server:
  port: 80

zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    grivet-admin: /admin/**
    grivet-ingest: /ingest/**
    grivet-persist: /persist/**
    grivet-query: /query/**
    grivet-standalone: /grivet/**
    springboot-admin: /bootadmin/**

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
  
---

spring:
  profiles: docker

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
