discovery:
  image: fastnsilver/grivet-discovery-service
  ports:
   - "8761:8761"
consulagent:
  image: progrium/consul
  ports:
   - "8500:8500"
   - "8400:8400"
   - "8600:53/udp"
  command: -server -bootstrap-expect 1 -ui-dir /ui
  net: host
consul:
  image: fastnsilver/grivet-consul
  ports:
   - "8000:8000"
  net: host
config:
  image: fastnsilver/grivet-config-service
  ports:
   - "8888:8888"
  links:
   - discovery
gateway:
  image: fastnsilver/grivet-api-gateway
  ports:
   - "10000:10000"
  links:
   - discovery
   - config
   - grivet
grivet:
  image: fastnsilver/grivet
  links:
   - discovery
   - config
