elasticsearch:
  build: elasticsearch/
  volumes_from:
    - elasticsearchData
  ports:
    - "9200:9200"

logstash:
  image: logstash:latest
  environment:
    TZ: America/Los_Angeles
  expose:
    - "12201"
  ports:
    - "12201:12201"
    - "12201:12201/udp"
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  links:
    - elasticsearch:db
  command: logstash -f /etc/logstash/conf.d/logstash.conf

kibana:
  build: kibana/
  ports:
    - "5601:5601"
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  links:
    - elasticsearch:elasticsearch

elasticsearchData:
  image: busybox
  command: "true"
  volumes:
    - ./data:/usr/share/elasticsearch/data

config:
  image: fastnsilver/grivet-config-server
  ports:
    - "8888:8888"
  links:
    - discovery
    
discovery:
  image: fastnsilver/grivet-discovery-service
  ports:
    - "8761:8761"

gateway:
  image: fastnsilver/grivet-api-gateway
  ports:
    - "8080:8080"
  links:
    - bootadmin
    - discovery
    - config
    - grivet

bootadmin:
  image: fastnsilver/grivet-boot-admin
  ports:
    - "5555:5555"
  links:
    - discovery
    - config

grivet:
  image: fastnsilver/grivet
  ports:
    - "8081:8081"
  links:
    - discovery
    - config
    - db
    
db:
  image: tutum/mysql:latest
  ports:
    - "3306:3306"
  env_file:
    - ./db.env
    
