elasticsearch:
  build: elasticsearch/
  volumes_from:
    - elasticsearchData
  ports:
    - "9200:9200"

logstash:
  image: logstash:latest
  environment:
    TZ: America/Los_Angeles
  expose:
    - "12201"
  ports:
    - "12201:12201"
    - "12201:12201/udp"
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  links:
    - elasticsearch:db
  command: logstash -f /etc/logstash/conf.d/logstash.conf

kibana:
  build: kibana/
  ports:
    - "5601:5601"
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  links:
    - elasticsearch:elasticsearch

elasticsearchData:
  image: busybox
  command: "true"
  volumes:
    - /usr/share/elasticsearch/data

discovery:
  image: fastnsilver/grivet-discovery-service
  ports:
    - "8761:8761"

consulagent:
  image: progrium/consul
  ports:
    - "8500:8500"
    - "8400:8400"
    - "8600:53/udp"
  command: -server -bootstrap-expect 1 -ui-dir /ui
  net: host

consul:
  image: fastnsilver/grivet-consul
  ports:
    - "8000:8000"
  net: host

config:
  image: fastnsilver/grivet-config-server
  ports:
    - "8888:8888"
  links:
    - discovery
   
gateway:
  image: fastnsilver/grivet-api-gateway
  ports:
    - "8080:8080"
  links:
    - bootadmin
    - discovery
    - config
    - grivet

bootadmin:
  image: fastnsilver/grivet-boot-admin
  ports:
    - "5555:5555"
  links:
    - discovery
    - config

grivet:
  image: fastnsilver/grivet
  ports:
    - "8081:8081"
  links:
    - discovery
    - config
