# WATCHTOWER
# @see https://github.com/CenturyLinkLabs/watchtower

# This file uses the version 2 docker-compose file format, described here:
# https://docs.docker.com/compose/compose-file/#version-2


## Be careful adding this service to your container cluster!  
## While it automates deployments, it can be a source of pain in development
## because unless you are publishing updated images to a private/public/trusted repository 
## on each (and every) build you can wind up troubelshooting container startup issues 
## that are oftentimes related to version/implementation incompatibilities

version: '2'

services:

  watchtower:
    image: centurylink/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock