server:
  port: 5555

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

logging:
  level:
    de.codecentric.boot.admin: DEBUG
 

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
        