# API GATEWAY

# This file uses the version 2 docker-compose file format, described here:
# https://docs.docker.com/compose/compose-file/#version-2

version: '2'

services:

  ### NETFLIX ZUUL
  zuul:
    image: fastnsilver/grivet-api-gateway
    ports:
      - 80:80
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx256m -XX:+UseG1GC -XX:+UseStringDeduplication
