info:
  version: @project.version@
spring:
  application:
    name: @project.artifactId@
  boot:
    admin:
      url: http://localhost:8080
  cloud:
    config:
      uri: ${SPRING_CONFIG_URI:http://localhost:8888}
      enabled: false
  profiles:
    active: h2
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    # Default settings; change at your own risk!
    initial-size: 10
    max-active: 75
    max-idle: 10
    min-idle: 5
    test-on-borrow: true
    remove-abandoned: false
    validation-query: SELECT 1
    validation-interval: 30000
    time-between-eviction-runs-millis: 5000
    min-evictable-idle-time-millis: 60000

flyway:
  placeholders:
    preamble:
    varcharQualifier: 
    createTableSuffix:
     
---

spring:
  profiles: hsqldb
  datasource:
    url: jdbc:hsqldb:mem:globaldb
    driver-class-name: org.hsqldb.jdbcDriver
    username: sa
    password: 
  jpa:
    show-sql: true
    properties:
      hibernate.connection.autocommit: true

flyway:
  locations: classpath:db/migration, classpath:db/hsqldb
  placeholders:
    autoInc: GENERATED BY DEFAULT AS IDENTITY
    dateTimeFormatFn: TO_CHAR(val, 'YYYY-MM-DD"T"HH24:MI:SS')
    textColumnType: VARCHAR(4000)
    longTextColumnType: VARCHAR(8000)
    
---

spring:
  profiles: h2
  datasource:
    url: jdbc:h2:mem:globaldb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

flyway:
  placeholders:
    autoInc: AUTO_INCREMENT
    dateTimeFormatFn: CONCAT(FORMATDATETIME(val, 'yyyy-MM-dd'), 'T', FORMATDATETIME(val, 'HH:mm:ss'))
    textColumnType: TEXT
    longTextColumnType: LONGTEXT
    
---

spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/globaldb
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: jackal#3

flyway:
  locations: classpath:db/with_partitions
  placeholders:
    preamble: |
      /*!40101 SET character_set_client = utf8 */;
      /*!40101 SET global innodb_file_format = BARRACUDA */;
      /*!40101 SET global innodb_large_prefix = ON */;
    autoInc: AUTO_INCREMENT 
    dateTimeFormatFn: DATE_FORMAT(val, '%Y-%m-%dT%T')
    textColumnType: TEXT
    longTextColumnType: LONGTEXT
    varcharQualifier: CHARACTER SET utf8 COLLATE utf8_bin
    createTableSuffix: ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC
