server:
  port: 8080
  
info:
  version: ${project.version}

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true
    
spring:
  profiles:
    active: h2,insecure
  cloud:
    config:
      discovery:
        enabled: false
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none

flyway:
  placeholders:
    preamble:
    varcharQualifier: 
    createTableSuffix:
    longVarBinary:
 
eureka:
  instance:
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
        
---

spring:
  profiles: hsqldb
  datasource:
    url: jdbc:hsqldb:mem:grivetdb
    driver-class-name: org.hsqldb.jdbcDriver
    data-source-class-name: org.hsqldb.jdbc.JDBCDataSource
    username: sa
    password: 
  jpa:
    show-sql: true
    properties:
      hibernate.connection.autocommit: true

flyway:
  locations: classpath:db/migration, classpath:db/hsqldb, classpath:db/users
  placeholders:
    autoInc: GENERATED BY DEFAULT AS IDENTITY
    dateTimeFormatFn: TO_CHAR(val, 'YYYY-MM-DD"T"HH24:MI:SS')
    textColumnType: VARCHAR(4000)
    longTextColumnType: VARCHAR(8000)
    longVarBinary: LONGVARBINARY
    
---

spring:
  profiles: h2
  datasource:
    url: jdbc:h2:mem:grivetdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    data-source-class-name: org.h2.jdbcx.JdbcDataSource
    username: sa
    password: sa

flyway:
  locations: classpath:db/migration, classpath:db/users
  placeholders:
    autoInc: AUTO_INCREMENT
    dateTimeFormatFn: CONCAT(FORMATDATETIME(val, 'yyyy-MM-dd'), 'T', FORMATDATETIME(val, 'HH:mm:ss'))
    textColumnType: TEXT
    longTextColumnType: LONGTEXT
    longVarBinary: LONGBLOB
    
---

spring:
  profiles: mysql
  profiles.include: basic
  #profiles.include: oauth2
  #profiles.include: https
  #profiles.include: oauth2,https
  datasource:
    url: jdbc:mysql://localhost:3306/grivetdb
    driver-class-name: com.mysql.jdbc.Driver
    data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    username: root
    password: jackal#3

flyway:
  locations: classpath:db/with_partitions, classpath:db/users, classpath:db/oauth2
  placeholders:
    preamble: |
      /*!40101 SET character_set_client = utf8 */;
      /*!40101 SET global innodb_file_format = BARRACUDA */;
      /*!40101 SET global innodb_large_prefix = ON */;
    autoInc: AUTO_INCREMENT 
    dateTimeFormatFn: DATE_FORMAT(val, '%Y-%m-%dT%T')
    textColumnType: TEXT
    longTextColumnType: LONGTEXT
    longVarBinary: LONGBLOB
    varcharQualifier: CHARACTER SET utf8 COLLATE utf8_bin
    createTableSuffix: ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC

---

spring:
  profiles: basic
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.oauth2.OAuth2AutoConfiguration
    
---

spring:
  profiles: insecure

management:
  security:
    enabled: false
    
security:
  basic:
    enabled: false
    
---

spring:
  profiles: https

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-password: password
  