server:
  port: 8888

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/  

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fastnsilver/spring-boot-microservice-config